# Server secret (dismiss the UI warning message)
webserverSecretKey: webserver-secret-key

# Git sync
dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/acardosolima/crypto-ethereum-tokens.git
    branch: develop
    subPath: "dev/src/airflow/dags/"
    period: 20s

# Job configurations
# Reference: https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false