name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master, develop]

jobs:
  validate:
    name: Validate terraform configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: [dev/src/terraform/, prod/src/terraform/]

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: [dev/src/terraform/, prod/src/terraform/]